### ISSUE TITLE
GCodeInfoV99.jar

### ISSUE THREAD

**Issue by hackwin** [dietzm/GCodeInfo#14]
GCodeInfoV99.jar produces the following errors.  Is it due to a Java update?

C:\Users\¿>"C:\Program Files\Java\jdk1.8.0_77\jre\bin\java.exe" -jar "c:/xampp/h
tdocs/GCodeInfoV99.jar" m "c:/xampp/htdocs/gCodeOutput/cube.stl.gcode" 2>&1
Load Model started
Parse GCODE GCDEF Exception:java.lang.IllegalArgumentException: No enum constant
 de.dietzm.Constants.GCDEF.M542
Unknown Gcode 179: UNKNOWN M542 ....
Parse GCODE GCDEF Exception:java.lang.IllegalArgumentException: No enum constant
 de.dietzm.Constants.GCDEF.M551
Unknown Gcode 180: UNKNOWN M551 P32000 S900....
Parse GCODE GCDEF Exception:java.lang.IllegalArgumentException: No enum constant
 de.dietzm.Constants.GCDEF.M543
Unknown Gcode 181: UNKNOWN M543 ....
Parse GCODE GCDEF Exception:java.lang.IllegalArgumentException: No enum constant
 de.dietzm.Constants.GCDEF.M542
Unknown Gcode 315: UNKNOWN M542 ....
Parse GCODE GCDEF Exception:java.lang.IllegalArgumentException: No enum constant
 de.dietzm.Constants.GCDEF.M551
Unknown Gcode 316: UNKNOWN M551 P32000 S900....
Parse GCODE GCDEF Exception:java.lang.IllegalArgumentException: No enum constant
 de.dietzm.Constants.GCDEF.M543
Unknown Gcode 317: UNKNOWN M543 ....
Load Model finished in ms:63
Detected 6 error(s) during parsing of Gcode file. Results might be wrong.
***************************************************************************
****************************** Model Details ******************************
***************************************************************************
Filename:  c:/xampp/htdocs/gCodeOutput/cube.stl.gcode
Layers visited:  75
Layers printed:  73
Avg.Layerheight: 0.35mm
Size:            24.54mm x 24.54mm H26.05mm
Position on bed: -11.27/13.27mm x -11.27/13.27mm H26.05mm
XY Distance:     34123.27mm
Extrusion:       0.0mm
Bed Temperatur:  0.0°
Ext Temperatur:  250.07°
Avg.Speed(All):    68.09mm/s
Avg.Speed(Print):  29.96mm/s
Avg.Speed(Travel): 103.7mm/s
Max.Speed(Print):  52.5mm/s
Min.Speed(Print):  10.0mm/s
Gcode Lines:     24227
Overall Time (w/o Acceleration):   0:25:04 (1503.74sec)
Overall Time (w/ Acceleration):    0:25:28 (1527.9677sec)
Material(guessed):ABS 3.0mm
Mass:   0.0cm3
Weight: 0.0g
Price:  0.0?

Gcode Analyse Time: 0:00:00 Load time:0:00:00

**Comment by dietzm** [comment]
GCodeInfo knows the most common gcodes only. M542,M543, etc. are not common and therefore GcodeInfo will print those warnings. It will not impact the parsing of the other gcodes.
